export const FAILED_TO_LOAD_GALLERIES = 'FAILED_TO_LOAD_GALLERIES';
export const GALLERIES_LOADED = 'GALLERIES_LOADED';
export const GALLERIES_CLEANED = 'GALLERIES_CLEANED';
export const PHOTO_VISIBILITY_CHANGED = 'PHOTO_VISIBILITY_CHANGED';
